server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        #路由的ID，没有固定规则但要求唯一，简易配合服务名
        - id: payment_routh
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
          uri: lb://cloud-provider-service
          #断言，路径相匹配的进行路由
          predicates:
            - Path=/payment/get/**

        #路由的ID，没有固定规则但要求唯一，简易配合服务名
        - id: payment_routh2
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
          uri: lb://cloud-provider-service
          #断言，路径相匹配的进行路由
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka


